use_frameworks!

target 'OSX-Cocoapods' do
  pod 'Nimble', path: '../Vendor/Nimble'
end

target 'OSX-CocoapodsTests' do
  pod 'Nimble', path: '../Vendor/Nimble'
end

target 'OSX-CocoapodsUITests' do
  pod 'Nimble', path: '../Vendor/Nimble'
end

