platform :osx, '10.11'
use_frameworks!

target 'OSX-Cocoapods' do
  # pod 'Quick', path: '../Vendor/Quick' # Quick doesn't support running without XCTest
  pod 'Nimble', path: '../Vendor/Nimble', branch: 'master'
end

target 'OSX-Cocoapods-QuickTests' do
  pod 'Quick', path: '../Vendor/Quick'
  pod 'Nimble', path: '../Vendor/Nimble', branch: 'master'
end

target 'OSX-Cocoapods-QuickUITests' do
  pod 'Quick', path: '../Vendor/Quick'
  pod 'Nimble', path: '../Vendor/Nimble', branch: 'master'
end

target 'OSX-Cocoapods-NimbleTests' do
  pod 'Nimble', path: '../Vendor/Nimble', branch: 'master'
end

target 'OSX-Cocoapods-NimbleUITests' do
  pod 'Nimble', path: '../Vendor/Nimble', branch: 'master'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
