platform :osx, '10.11'
use_frameworks!

target 'OSX-Cocoapods' do
  # pod 'Quick', path: '../Vendor/Quick' # Quick doesn't support running without XCTest
  pod 'Nimble', path: '../Vendor/Nimble'
end

target 'OSX-Cocoapods-QuickTests' do
  pod 'Quick', path: '../Vendor/Quick'
  pod 'Nimble', path: '../Vendor/Nimble'
end

target 'OSX-Cocoapods-QuickUITests' do
  pod 'Quick', path: '../Vendor/Quick'
  pod 'Nimble', path: '../Vendor/Nimble'
end

target 'OSX-Cocoapods-NimbleTests' do
  pod 'Nimble', path: '../Vendor/Nimble'
end

target 'OSX-Cocoapods-NimbleUITests' do
  pod 'Nimble', path: '../Vendor/Nimble'
end
