use_frameworks!

target 'iOS-Cocoapods' do
  pod 'Nimble', path: '../Vendor/Nimble'
end

target 'iOS-CocoapodsTests' do
  pod 'Nimble', path: '../Vendor/Nimble'
end

target 'iOS-CocoapodsUITests' do
  pod 'Nimble', path: '../Vendor/Nimble'
end

